# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Keep pubspec.yaml (Flutter/Dart dependencies) up to date
  - package-ecosystem: "pub"
    directory: "/" # Location of pubspec.yaml
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "salah-rashad"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/" # Location of workflow files in .github/workflows
    schedule:
      interval: "weekly"
    reviewers:
      - "salah-rashad"

